package edu.uob;

public enum SyntaxType {
    USE, CREATE_DATABASE, CREATE_TABLE, DROP,
    ALTER, INSERT, SELECT, CONDITION,
    UPDATE, DELETE, JOIN, AND, ADD, OR,
    ERROR, VALUE,
    DATABASE_NAME, TABLE_NAME, ATTRIBUTE_NAME,
    SELECT_ALL,
    EQUAL_TO, LT, LT_EQUAL_TO, GT, GT_EQUAL_TO, NOT_EQUAL, LIKE,
    STRING_LITERAL, BOOLEAN_LITERAL, FLOAT_LITERAL, INTEGER_LITERAL, NULL_VALUE

}
